name: pomodoro_app
description: "Pomodoro Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  audioplayers: ^6.5.1
  confetti: ^0.8.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/translations/
    - assets/icon/

# --- İKON AYARLARI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

# --- HAYALET SPLASH AYARLARI (Yeni Eklenen Kısım) ---
flutter_native_splash:
  # Arka plan rengini senin Splash ekranındaki koyu mod rengiyle aynı yaptık (#1E1E2C).
  # Böylece uygulama açılınca boş bir ekran gelir, sonra senin animasyon başlar.
  color: "#1E1E2C"

  # Android 12+ mecburen bir ikon göstermek ister, arka planı uyumlu yapıyoruz.
  android_12:
    image: "assets/icon/transparent.png"
    icon_background_color: "#1E1E2C"